#!/bin/sh
#
# install-appimage.sh: install PyReconstruct on Linux from its AppImage.
#
#   curl -fsSL https://pyreconstruct.org/install.sh | bash
#   curl -fsSL https://pyreconstruct.org/install.sh | bash -s -- --dev          # PyReconstruct Dev
#   curl -fsSL https://pyreconstruct.org/install.sh | bash -s -- --uninstall    # add --dev for Dev
#
# The docs workflow publishes this file as pyreconstruct.org/install.sh.
#
# Per user, no root. Downloads the newest AppImage for the chosen app from the
# GitHub releases, checks it against its published .sha256, and adds a launcher
# (~/.local/bin/pyreconstruct or pyreconstruct-dev), a menu entry, an icon and
# the .jser file type under ~/.local/share. Re-running upgrades in place; a run
# that is already current only refreshes the menu entry. The stable app and
# PyReconstruct Dev use separate names throughout, so they install side by side.
#
# Which release, mirroring the in-app updater's strict channels:
#   stable  the repository's latest release (releases/latest), never a pre-release
#   --dev   the newest pre-release whose tag is a nightly (vX.Y.Z.devYYYYMMDDHHMM,
#           or the older vX.Y.Z.devYYYYMMDD),
#           never a stable release, a release candidate, or a draft
#
# Plain POSIX sh: runs under bash, dash, and busybox ash.
#
# Environment overrides:
#   GITHUB_TOKEN           sent to the GitHub API only, to lift the anonymous rate limit
#   PYRECON_RELEASES_API   API base for the repository (for tests and mirrors);
#                          plain http is accepted only for localhost

set -eu

REPO="dustenhubbard/PyReconstruct"
INSTALLER_URL="https://pyreconstruct.org/install.sh"
API="${PYRECON_RELEASES_API:-https://api.github.com/repos/$REPO}"
NIGHTLY_RE='^v[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]{8}([0-9]{4})?$'
ROLLING_TAG="prerelease"
MIME_TYPE="application/x-pyreconstruct-jser"
GLIBC_MIN="2.28"

say()  { printf '==> %s\n' "$*" >&2; }
note() { printf '    %s\n' "$*" >&2; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

usage() {
  cat >&2 <<EOF
Install PyReconstruct from its AppImage.

Usage:
  install-appimage.sh [--dev]               install, or upgrade in place
  install-appimage.sh --uninstall [--dev]   remove it
  install-appimage.sh --help

  --dev        PyReconstruct Dev, the nightly build (installs beside PyReconstruct)
  --uninstall  remove PyReconstruct, its launcher, menu entry, icon and file type

Piped from curl, pass options after "bash -s --":
  curl -fsSL $INSTALLER_URL | bash -s -- --dev
EOF
}

# ------------------------------------------------------------------ arguments
FLAVOR="stable"
MODE="install"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dev)       FLAVOR="dev" ;;
    --stable)    FLAVOR="stable" ;;
    --uninstall) MODE="uninstall" ;;
    -h|--help)   usage; exit 0 ;;
    *)           printf 'error: unknown option: %s\n\n' "$1" >&2; usage; exit 2 ;;
  esac
  shift
done

if [ "$FLAVOR" = "dev" ]; then
  APP_NAME="PyReconstruct Dev"
  APP_ID="edu.utexas.synapseweb.pyreconstruct.dev"
  COMMAND="pyreconstruct-dev"
  LOCAL_FILE="PyReconstruct-Dev.AppImage"
  ASSET_RE='^PyReconstruct-[0-9][^/-]*-linux-x86_64-Dev\.AppImage$'
  FLAG=" --dev"
else
  APP_NAME="PyReconstruct"
  APP_ID="edu.utexas.synapseweb.pyreconstruct"
  COMMAND="pyreconstruct"
  LOCAL_FILE="PyReconstruct.AppImage"
  ASSET_RE='^PyReconstruct-[0-9][^/-]*-linux-x86_64\.AppImage$'
  FLAG=""
fi

# ---------------------------------------------------------------------- paths
[ -n "${HOME:-}" ] || die "HOME is not set, so there is nowhere to install"
case "$HOME" in /*) ;; *) die "HOME is not an absolute path: $HOME" ;; esac
# The XDG base directory spec says to ignore a relative value.
DATA_HOME="${XDG_DATA_HOME:-}"
case "$DATA_HOME" in /*) ;; *) DATA_HOME="$HOME/.local/share" ;; esac
BIN_DIR="${XDG_BIN_HOME:-}"
case "$BIN_DIR" in /*) ;; *) BIN_DIR="$HOME/.local/bin" ;; esac

APPROOT="$DATA_HOME/$APP_NAME"
APPIMAGE="$APPROOT/$LOCAL_FILE"
MARKER="$APPROOT/.appimage-install"
LOCK_DIR="$APPROOT/.install-lock"
LAUNCHER="$BIN_DIR/$COMMAND"
APPS_DIR="$DATA_HOME/applications"
DESKTOP="$APPS_DIR/$APP_ID.desktop"
HICOLOR="$DATA_HOME/icons/hicolor"
ICON="$HICOLOR/512x512/apps/$APP_ID.png"
MIME_DIR="$DATA_HOME/mime"
MIME_XML="$MIME_DIR/packages/$APP_ID.xml"
LAUNCHER_TAG="generated by install-appimage.sh"

UNINSTALL_HINT="curl -fsSL $INSTALLER_URL | bash -s -- --uninstall$FLAG"

refresh_caches() {
  if have update-desktop-database; then update-desktop-database "$APPS_DIR" >/dev/null 2>&1 || true; fi
  if have update-mime-database; then update-mime-database "$MIME_DIR" >/dev/null 2>&1 || true; fi
  if have gtk-update-icon-cache; then gtk-update-icon-cache -f -t "$HICOLOR" >/dev/null 2>&1 || true; fi
}

# ------------------------------------------------------------------ uninstall
if [ "$MODE" = "uninstall" ]; then
  if [ ! -e "$MARKER" ] && [ ! -e "$APPIMAGE" ] && [ ! -e "$DESKTOP" ] && [ ! -e "$LAUNCHER" ]; then
    say "$APP_NAME is not installed from its AppImage here (nothing at $APPROOT)."
    exit 0
  fi
  if [ -d "$APPROOT" ] && ! mkdir "$LOCK_DIR" 2>/dev/null; then
    die "an install of $APP_NAME seems to be running (lock: $LOCK_DIR). If none is, remove that folder and re-run."
  fi
  trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT
  if [ -e "$LAUNCHER" ]; then
    # Only a launcher this script wrote; never someone else's command.
    if grep -q "$LAUNCHER_TAG" "$LAUNCHER" 2>/dev/null; then
      rm -f "$LAUNCHER" && note "removed $LAUNCHER"
    else
      warn "left $LAUNCHER in place: this installer did not write it"
    fi
  fi
  for f in "$DESKTOP" "$ICON" "$MIME_XML" "$APPIMAGE" "$MARKER"; do
    if [ -f "$f" ] || [ -L "$f" ]; then rm -f "$f" && note "removed $f"; fi
  done
  rmdir "$LOCK_DIR" 2>/dev/null || true
  if [ -d "$APPROOT" ]; then
    if rmdir "$APPROOT" 2>/dev/null; then
      note "removed $APPROOT"
    else
      warn "left $APPROOT in place: it holds files this installer did not create"
    fi
  fi
  refresh_caches
  say "$APP_NAME uninstalled. Your series files and settings were not touched."
  exit 0
fi

# ------------------------------------------------------------------ preflight
[ "$(uname -s 2>/dev/null || echo unknown)" = "Linux" ] || die "this installer is for Linux; see the releases page for Windows and macOS: https://github.com/$REPO/releases"
case "$(uname -m 2>/dev/null || echo unknown)" in
  x86_64|amd64) ;;
  *) die "only an x86_64 AppImage is published; this machine is $(uname -m 2>/dev/null || echo unknown)" ;;
esac

# glibc: the AppImage is built on glibc $GLIBC_MIN (RHEL 8, Ubuntu 20.04, Debian 10 and later).
if have getconf; then
  glibc="$(getconf GNU_LIBC_VERSION 2>/dev/null | awk '{print $2}')" || glibc=""
  if [ -n "$glibc" ]; then
    if ! printf '%s\n' "$glibc" | awk -v min="$GLIBC_MIN" '
      { split($0, a, "."); split(min, b, ".");
        exit !((a[1] + 0 > b[1] + 0) || (a[1] + 0 == b[1] + 0 && a[2] + 0 >= b[2] + 0)) }'; then
      die "PyReconstruct needs glibc $GLIBC_MIN or newer; this system has $glibc"
    fi
  fi
fi

if have curl; then DL="curl"; elif have wget; then DL="wget"; else
  die "curl or wget is needed to download PyReconstruct; install one (for example: sudo apt install curl) and re-run"
fi
if have sha256sum; then SHA="sha256sum"; elif have shasum; then SHA="shasum -a 256"; else
  die "sha256sum is needed to check the download (it is part of coreutils)"
fi

# plain http only for a local test server; everything real is https
check_url() {
  case "$1" in
    https://*|http://127.0.0.1:*|http://127.0.0.1/*|http://localhost:*|http://localhost/*) ;;
    *) die "refusing a non-https URL: $1" ;;
  esac
}

# fetch URL: the body on stdout; the token goes to the API only
fetch_api() {
  check_url "$1"
  if [ "$DL" = "curl" ]; then
    if [ -n "${GITHUB_TOKEN:-}" ]; then
      curl -fsSL --proto-redir =https --retry 3 -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" "$1"
    else
      curl -fsSL --proto-redir =https --retry 3 -H "Accept: application/vnd.github+json" "$1"
    fi
  else
    if [ -n "${GITHUB_TOKEN:-}" ]; then
      wget -q -O - --header="Accept: application/vnd.github+json" --header="Authorization: Bearer $GITHUB_TOKEN" "$1"
    else
      wget -q -O - --header="Accept: application/vnd.github+json" "$1"
    fi
  fi
}

# download URL FILE
download() {
  check_url "$1"
  if [ "$DL" = "curl" ]; then
    if [ -t 2 ]; then curl -fL --proto-redir =https --retry 3 -# -o "$2" "$1"; else curl -fsSL --proto-redir =https --retry 3 -o "$2" "$1"; fi
  else
    # wget has no option to limit a redirect to https; the .sha256 check below
    # still refuses a file that does not match.
    wget -q -O "$2" "$1"
  fi
}

sha256_of() { $SHA "$1" | awk '{print $1}'; }

# A script-based install (install.sh, a Python virtual environment) keeps its
# files in the same folder and owns the same command. Replacing it silently
# would leave its uninstaller able to delete this app, so ask for it to go first.
if [ -f "$APPROOT/.pyreconstruct-install" ]; then
  die "a script-based install of $APP_NAME (install.sh) is in $APPROOT.
Remove it first, then re-run this installer:
    bash \"$APPROOT/uninstall.sh\""
fi

# ----------------------------------------------------------------------- lock
# The trap is set before the first mkdir, so a first install that stops at the
# permission checks below leaves no empty folder either.
# Scratch files live in WORK, inside APPROOT so the finished download renames
# into place on the same file system. TMP_L and TMP_D sit beside their targets
# for the same reason. Each is removed by name: APPROOT may contain a space.
WORK=""
TMP_L=""
TMP_D=""
OWN_LOCK=""
cleanup() {
  if [ -n "$WORK" ]; then rm -rf "$WORK" 2>/dev/null || true; fi
  if [ -n "$TMP_L" ]; then rm -f "$TMP_L" 2>/dev/null || true; fi
  if [ -n "$TMP_D" ]; then rm -f "$TMP_D" 2>/dev/null || true; fi
  if [ -n "$OWN_LOCK" ]; then rmdir "$OWN_LOCK" 2>/dev/null || true; fi
  # a first install that failed leaves no empty folder behind
  rmdir "$APPROOT" 2>/dev/null || true
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
mkdir -p "$APPROOT" "$BIN_DIR" "$APPS_DIR" "$HICOLOR/512x512/apps" "$MIME_DIR/packages" 2>/dev/null || true
for d in "$APPROOT" "$BIN_DIR" "$APPS_DIR" "$HICOLOR/512x512/apps" "$MIME_DIR/packages"; do
  { [ -d "$d" ] && [ -w "$d" ]; } || die "cannot write to $d; check its permissions"
done
if [ -e "$LAUNCHER" ] && ! grep -q "$LAUNCHER_TAG" "$LAUNCHER" 2>/dev/null; then
  die "$LAUNCHER already exists and this installer did not write it; move it aside and re-run"
fi

if mkdir "$LOCK_DIR" 2>/dev/null; then
  OWN_LOCK="$LOCK_DIR"
else
  die "another install of $APP_NAME seems to be running (lock: $LOCK_DIR). If none is, remove that folder and re-run."
fi
WORK="$(mktemp -d "$APPROOT/.work.XXXXXX")" || die "cannot create a scratch folder in $APPROOT"

# ------------------------------------------------------------ pick the release
# The API's JSON is read with grep and awk, not a JSON parser, so this runs on
# a desktop with nothing extra installed. Only four keys matter. Each release
# lists tag_name, then draft and prerelease, then its assets; the tag an asset
# belongs to is read from its own download URL (.../download/<tag>/<name>), so
# an asset can never be credited to the wrong release. Quotes inside strings
# (a release body) are escaped, so they never match the key patterns.
list_assets() {
  grep -oE '"(tag_name|browser_download_url)"[[:space:]]*:[[:space:]]*"[^"]*"|"(draft|prerelease)"[[:space:]]*:[[:space:]]*(true|false)' |
  awk '
    {
      key = $0; sub(/^"/, "", key); sub(/".*/, "", key)
      val = $0; sub(/^"[^"]*"[ \t]*:[ \t]*/, "", val); gsub(/"/, "", val)
      if (key == "tag_name") { tag = val; order[++n] = val; pre[val] = "?"; drf[val] = "?" }
      else if (key == "prerelease") { pre[tag] = val }
      else if (key == "draft") { drf[tag] = val }
      else if (key == "browser_download_url") {
        m = split(val, p, "/")
        if (m >= 3) { at = p[m - 1]; nm = p[m]; urls[++k] = at "\t" nm "\t" val }
      }
    }
    END {
      # releases in API order (newest first); each release its assets
      for (i = 1; i <= n; i++) {
        t = order[i]
        for (j = 1; j <= k; j++) {
          split(urls[j], f, "\t")
          if (f[1] == t) print t "\t" pre[t] "\t" drf[t] "\t" f[2] "\t" f[3]
        }
      }
    }'
}

say "Looking up the newest $APP_NAME release"
if [ "$FLAVOR" = "dev" ]; then
  API_URL="$API/releases?per_page=100"
else
  API_URL="$API/releases/latest"
fi
TMP_JSON="$WORK/releases.json"
if ! fetch_api "$API_URL" >"$TMP_JSON"; then
  die "could not read the release list from $API_URL
(offline, or GitHub's hourly limit for anonymous requests; wait, or set GITHUB_TOKEN, and re-run)"
fi
ASSETS="$(list_assets <"$TMP_JSON")" || ASSETS=""

TAG=""; ASSET_NAME=""; ASSET_URL=""; SHA_URL=""; NEWEST=""
TAB="$(printf '\t')"
while IFS="$TAB" read -r a_tag a_pre a_draft a_name a_url; do
  [ -n "$a_tag" ] || continue
  [ "$a_draft" = "true" ] && continue
  if [ "$FLAVOR" = "dev" ]; then
    [ "$a_pre" = "true" ] || continue
    [ "$a_tag" != "$ROLLING_TAG" ] || continue
    printf '%s\n' "$a_tag" | grep -Eq "$NIGHTLY_RE" || continue
  else
    [ "$a_pre" = "false" ] || continue
  fi
  [ -n "$NEWEST" ] || NEWEST="$a_tag"
  if [ -z "$TAG" ] && printf '%s\n' "$a_name" | grep -Eq "$ASSET_RE"; then
    TAG="$a_tag"; ASSET_NAME="$a_name"; ASSET_URL="$a_url"
  fi
done <<EOF
$ASSETS
EOF

if [ -z "$TAG" ]; then
  if [ "$FLAVOR" = "dev" ]; then
    die "no nightly release has a Linux AppImage for $APP_NAME yet: https://github.com/$REPO/releases"
  else
    die "the latest release${NEWEST:+ ($NEWEST)} has no Linux AppImage for $APP_NAME yet: https://github.com/$REPO/releases/latest"
  fi
fi
if [ "$TAG" != "$NEWEST" ]; then
  warn "the newest nightly ($NEWEST) has no Linux AppImage; installing $TAG instead"
fi
while IFS="$TAB" read -r a_tag a_pre a_draft a_name a_url; do
  if [ "$a_tag" = "$TAG" ] && [ "$a_name" = "$ASSET_NAME.sha256" ]; then SHA_URL="$a_url"; fi
done <<EOF
$ASSETS
EOF
[ -n "$SHA_URL" ] || die "$TAG has no $ASSET_NAME.sha256, so the download cannot be checked; not installing it"

# ------------------------------------------------------------------ download
TMP_SHA="$WORK/asset.sha256"
download "$SHA_URL" "$TMP_SHA" || die "could not download $SHA_URL"
EXPECTED="$(awk 'NR == 1 {print tolower($1)}' "$TMP_SHA")"
printf '%s\n' "$EXPECTED" | grep -Eq '^[0-9a-f]{64}$' || die "$ASSET_NAME.sha256 does not hold a SHA-256 checksum"

INSTALLED_TAG=""
if [ -f "$MARKER" ]; then INSTALLED_TAG="$(sed -n 's/^tag=//p' "$MARKER" | head -n 1)"; fi

if [ "$INSTALLED_TAG" = "$TAG" ] && [ -f "$APPIMAGE" ] && [ "$(sha256_of "$APPIMAGE")" = "$EXPECTED" ]; then
  say "$APP_NAME $TAG is already installed; refreshing the launcher and menu entry"
else
  say "Downloading $ASSET_NAME ($TAG)"
  TMP_AI="$WORK/download.AppImage"
  download "$ASSET_URL" "$TMP_AI" || die "could not download $ASSET_URL"
  ACTUAL="$(sha256_of "$TMP_AI")"
  if [ "$ACTUAL" != "$EXPECTED" ]; then
    die "the download does not match its published checksum, so it was not installed.
    expected $EXPECTED
    got      $ACTUAL
Re-run to try again."
  fi
  note "checksum OK"
  chmod 0755 "$TMP_AI"
  # rename in place: an instance that is running keeps its open file
  mv -f "$TMP_AI" "$APPIMAGE"
fi

# ------------------------------------------------------------ desktop files
# The menu entry, icon and file type ship inside the AppImage itself;
# --appimage-extract reads them out without FUSE.
EXTRACT="$WORK/extract"
mkdir -p "$EXTRACT"
SHARE="$EXTRACT/squashfs-root/usr/share"
( cd "$EXTRACT" && "$APPIMAGE" --appimage-extract 'usr/share/*' >/dev/null 2>&1 ) || true
[ -d "$SHARE" ] || warn "could not read the menu entry and icon from the AppImage; writing a plain menu entry"

# the launcher, with single quotes escaped for the sh literal
q_path="$(printf '%s' "$APPIMAGE" | sed "s/'/'\\\\''/g")"
TMP_L="$BIN_DIR/.$COMMAND.$$"
cat >"$TMP_L" <<EOF
#!/bin/sh
# $APP_NAME launcher, $LAUNCHER_TAG.
# Re-run the installer to upgrade; see its --uninstall option to remove.
APPIMAGE_PATH='$q_path'
# Without FUSE the AppImage cannot mount itself; unpack to a temporary folder instead.
if [ -z "\${APPIMAGE_EXTRACT_AND_RUN:-}" ]; then
  if [ ! -c /dev/fuse ] || ! { command -v fusermount3 >/dev/null 2>&1 || command -v fusermount >/dev/null 2>&1; }; then
    APPIMAGE_EXTRACT_AND_RUN=1
    export APPIMAGE_EXTRACT_AND_RUN
  fi
fi
exec "\$APPIMAGE_PATH" "\$@"
EOF
chmod 0755 "$TMP_L"
mv -f "$TMP_L" "$LAUNCHER"
TMP_L=""
note "launcher: $LAUNCHER"

# Exec is quoted per the desktop entry spec: \ " \` \$ escaped, % doubled.
exec_path="$(printf '%s' "$LAUNCHER" | sed -e 's/[\\"`$]/\\\\&/g' -e 's/%/%%/g')"
TMP_D="$APPS_DIR/.$APP_ID.$$"
if [ -f "$SHARE/applications/$APP_ID.desktop" ]; then
  # through the environment: awk -v would undo the backslash escapes
  EXEC_LINE="Exec=\"$exec_path\" %f" TRY_LINE="TryExec=$LAUNCHER" awk '
    /^Exec=/ { print ENVIRON["EXEC_LINE"]; print ENVIRON["TRY_LINE"]; next }
    /^TryExec=/ { next }
    { print }' "$SHARE/applications/$APP_ID.desktop" >"$TMP_D"
else
  cat >"$TMP_D" <<EOF
[Desktop Entry]
Type=Application
Name=$APP_NAME
Exec="$exec_path" %f
TryExec=$LAUNCHER
Icon=$APP_ID
Terminal=false
Categories=Science;Biology;
MimeType=$MIME_TYPE;
EOF
fi
chmod 0644 "$TMP_D"
mv -f "$TMP_D" "$DESKTOP"
TMP_D=""
note "menu entry: $DESKTOP"

if [ -f "$SHARE/icons/hicolor/512x512/apps/$APP_ID.png" ]; then
  cp "$SHARE/icons/hicolor/512x512/apps/$APP_ID.png" "$ICON" && chmod 0644 "$ICON"
fi
if [ -f "$SHARE/mime/packages/$APP_ID.xml" ]; then
  cp "$SHARE/mime/packages/$APP_ID.xml" "$MIME_XML"
else
  cat >"$MIME_XML" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="$MIME_TYPE">
    <comment>PyReconstruct series</comment>
    <sub-class-of type="application/json"/>
    <glob pattern="*.jser"/>
  </mime-type>
</mime-info>
EOF
fi
chmod 0644 "$MIME_XML"
refresh_caches

# A double-clicked .jser opens in the stable app when both are installed, as on
# macOS. Only claimed when nothing, or PyReconstruct Dev, holds the default.
if [ "$FLAVOR" = "stable" ] && have xdg-mime; then
  current="$(xdg-mime query default "$MIME_TYPE" 2>/dev/null || true)"
  if [ -z "$current" ] || [ "$current" = "edu.utexas.synapseweb.pyreconstruct.dev.desktop" ]; then
    xdg-mime default "$APP_ID.desktop" "$MIME_TYPE" >/dev/null 2>&1 || true
  fi
fi

{
  printf 'flavor=%s\n' "$FLAVOR"
  printf 'tag=%s\n' "$TAG"
  printf 'asset=%s\n' "$ASSET_NAME"
  printf 'sha256=%s\n' "$EXPECTED"
} >"$MARKER"

# -------------------------------------------------------------------- summary
printf '\n' >&2
say "$APP_NAME $TAG is installed."
note "AppImage:    $APPIMAGE"
note "Open it from your application menu, or run: $COMMAND"
case ":${PATH:-}:" in
  *":$BIN_DIR:"*) ;;
  *) note "($BIN_DIR is not on your PATH; add it, or run $LAUNCHER)" ;;
esac
if [ ! -c /dev/fuse ] || ! { have fusermount3 || have fusermount; }; then
  note "FUSE is not available, so each launch unpacks $APP_NAME first and starts more slowly."
  note "Installing FUSE (the fuse3 package on most distributions) makes launches fast."
fi
printf '\n' >&2
note "Upgrade:    re-run this installer"
note "Uninstall:  $UNINSTALL_HINT"
